[tool.poetry]
name = "p1"
version = "0.1.0"
description = "Package 1"
authors = ["gabriel furnieles <gabifurnielesgarcia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
